# Generated by Django 5.0.1 on 2026-02-15 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="InventoryItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("hydration", "Hydration"),
                            ("food", "Food"),
                            ("medical", "Medical"),
                            ("shelter", "Shelter"),
                            ("equipment", "Equipment"),
                        ],
                        max_length=20,
                    ),
                ),
                ("unit", models.CharField(max_length=20)),
                ("current_stock", models.IntegerField(default=0)),
                ("minimum_stock", models.IntegerField(default=0)),
                ("per_person_per_day", models.FloatField(blank=True, null=True)),
                ("per_household", models.FloatField(blank=True, null=True)),
                ("guideline_source", models.CharField(blank=True, max_length=100)),
                ("guideline_note", models.TextField(blank=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["category", "name"],
            },
        ),
        migrations.CreateModel(
            name="Warehouse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("address", models.CharField(max_length=200)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("capacity", models.IntegerField()),
                ("utilization", models.IntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("operational", "Operational"),
                            ("limited", "Limited"),
                            ("offline", "Offline"),
                        ],
                        default="operational",
                        max_length=20,
                    ),
                ),
            ],
        ),
    ]
