# Generated by Django 5.0.1 on 2026-02-15 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vehicle_id", models.CharField(max_length=20, unique=True)),
                (
                    "vehicle_type",
                    models.CharField(
                        choices=[
                            ("ambulance", "Ambulance"),
                            ("fire_truck", "Fire Truck"),
                            ("supply_truck", "Supply Truck"),
                            ("rescue", "Rescue"),
                            ("command", "Command"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "Available"),
                            ("en_route", "En Route"),
                            ("on_scene", "On Scene"),
                            ("returning", "Returning"),
                            ("maintenance", "Maintenance"),
                        ],
                        default="available",
                        max_length=20,
                    ),
                ),
                ("driver_name", models.CharField(blank=True, max_length=100)),
                ("latitude", models.FloatField(default=30.2672)),
                ("longitude", models.FloatField(default=-97.7431)),
                ("destination", models.CharField(blank=True, max_length=200)),
                ("dispatched_at", models.DateTimeField(blank=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-last_updated"],
            },
        ),
    ]
