# Generated by Django 5.0.1 on 2026-02-15 16:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Alert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("minor", "Minor"),
                            ("moderate", "Moderate"),
                            ("severe", "Severe"),
                            ("extreme", "Extreme"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("acknowledged", "Acknowledged"),
                            ("resolved", "Resolved"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("source", models.CharField(default="local", max_length=50)),
                ("external_id", models.CharField(blank=True, max_length=100)),
                ("areas_affected", models.CharField(blank=True, max_length=500)),
                ("instructions", models.TextField(blank=True)),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                (
                    "effective_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-effective_at"],
            },
        ),
        migrations.CreateModel(
            name="Incident",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "incident_type",
                    models.CharField(
                        choices=[
                            ("traffic", "Traffic"),
                            ("weather", "Weather"),
                            ("infrastructure", "Infrastructure"),
                            ("medical", "Medical"),
                            ("fire", "Fire"),
                            ("flood", "Flooding"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("moderate", "Moderate"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="moderate",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("reported", "Reported"),
                            ("confirmed", "Confirmed"),
                            ("responding", "Responding"),
                            ("resolved", "Resolved"),
                        ],
                        default="reported",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField()),
                ("location", models.CharField(blank=True, max_length=200)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("reported_at", models.DateTimeField(auto_now_add=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-reported_at"],
            },
        ),
    ]
