# Generated by Django 5.0.1 on 2026-02-15 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Shelter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("address", models.CharField(max_length=300)),
                ("city", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=2)),
                ("zip_code", models.CharField(max_length=10)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("capacity", models.IntegerField()),
                ("occupancy", models.IntegerField(default=0)),
                ("is_open", models.BooleanField(default=False)),
                ("is_pet_friendly", models.BooleanField(default=False)),
                ("is_ada_compliant", models.BooleanField(default=True)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("notes", models.TextField(blank=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["state", "city", "name"],
            },
        ),
    ]
